from selenium import webdriver
import time
import sys
import getpass

# reload(sys)
# sys.setdefaultencoding('utf-8')


input_username = input("enter github username: ")
input_password = getpass.getpass() 

time.sleep(1)

# Chrome used
driver = webdriver.Chrome(executable_path='C:/Selenium/chromedriver.exe')
# base url
driver.get("http://github.com/login")

username = driver.find_element_by_id("login_field")
password = driver.find_element_by_id("password")

# password and username need to go into these values
username.send_keys(f"{input_username}")
time.sleep(1)
password.send_keys(f"{input_password}")
time.sleep(1)

login_form = driver.find_element_by_xpath("//input[@value='Sign in']")
time.sleep(1)
login_form.click()
time.sleep(1)

# These are some of the most popular users on github
# prepend = ["jlord", "daimajia", "mdo", "schacon", "mattt",
#            "sindresorhus", "defunkt", "douglascrockford", "mbostock", "jeresig",
#            "mojombo", "addyosmani", "paulirish", "vczh", "romannurik", "tenderlove", "chriscoyier", "johnpapa",
#            "josevalim","charliesome", "CoderMJLee", "ry", "antirez", "muan", "isaacs", "angusshire",
#            "hadley", "hakimel", "yyx990803", "fat", "fabpot", "ibireme", "tekkub",
#            "BYVoid", "laruence", "onevcat", "tpope", "mrdoob", "LeaVerou", "chrisbanes", "wycats", "lifesinger",
#            "cloudwu", "mitsuhiko", "michaelliao", "ryanb", "clowwindy", "JacksonTian", "yinwang0", "Trinea",
#            "pjhyett", "dhh", "gaearon"]
prepend=["fabpot",
"andrew",
"taylorotwell",
"egoist",
"HugoGiraudel",
"ornicar",
"bebraw",
"nelsonic",
"alexcrichton",
"jonathanong",
"mikermcneil",
"benbalter",
"jxnblk",
"yegor256",
"orta",
"rstacruz",
"GrahamCampbell",
"afc163",
"kamranahmedse",
"joshaber",
"bkeepers",
"kennethreitz",
"kytrinyx",
"STRML",
"atmos",
"weierophinney",
"agentzh",
"steipete",
"ai",
"mikepenz",
"nvie",
"hadley",
"appleboy",
"Rich-Harris",
"drnic",
"rafaelfranca",
"Ocramius",
"mitchellh",
"stof",
"IgorMinar",
"phodal",
"jwiegley",
"geerlingguy",
"dcramer",
"sebastianbergmann",
"brunocvcunha",
"ljharb",
"jdalton",
"sevilayha",
"paulmillr",
"tmm1",
"c9s",
"zcbenz",
"holman",
"kevinsawicki",
"yihui",
"buckyroberts",
"kbrsh",
"dmalan",
"mhevery",
"mgechev",
"kylef",
"chjj",
"ayende",
"mcollina",
"mdo",
"yoshuawuyts",
"muan",
"kentcdodds",
"jskeet",
"mitsuhiko",
"steveklabnik",
"hzoo",
"Caged",
"dlew",
"technoweenie",
"gaearon",
"soumith",
"feross",
"michalbe",
"brianleroux",
"willdurand",
"alexjlockwood",
"matsko",
"stefanpenner",
"adamwathan",
"Haacked",
"curran",
"rauchg",
"ianstormtaylor",
"KrauseFx",
"tj",
"jgm",
"jverkoey",
"chenglou",
"DataTables",
"SamyPesse",
"mjhea0",
"0x00A",
"tmcw",
"brentvatne",
"carpedm20",
"benjamn",
"notwaldorf",
"miyagawa",
"rnystrom",
"photonstorm",
"mattn",
"dougwilson",
"JakeWharton",
"yyx990803",
"krzysztofzablocki",
"eduardolundgren",
"vjeux",
"mxcl",
"domenic",
"alex",
"mrdoob",
"josegonzalez",
"fzaninotto",
"pissang",
"jamesmontemagno",
"paulcbetts",
"paulirish",
"samdark",
"madskristensen",
"sokra",
"marijnh",
"alanhamlett",
"wesm",
"josevalim",
"jennybc",
"BurntSushi",
"zenorocha",
"contra",
"jaredhanson",
"radar",
"bevacqua",
"xudafeng",
"j2kun",
"dominictarr",
"avelino",
"vinta",
"developit",
"ashleygwilliams",
"ashfurrow",
"f",
"onevcat",
"toddmotto",
"gdi2290",
"EisenbergEffect",
"ankane",
"keijiro",
"nolimits4web",
"davidfowl",
"biezhi",
"LeaVerou",
"davidtmiller",
"odersky",
"vhf",
"soffes",
"mxstbr",
"Jinjiang",
"happypeter",
"yeasy",
"mafintosh",
"vczh",
"Draveness",
"ded",
"vladikoff",
"bnoordhuis",
"jendewalt",
"jessfraz",
"indutny",
"olivergierke",
"i5ting",
"laanwj",
"drakeet",
"thejameskyle",
"ahmetb",
"sdiehl",
"jaywcjlove",
"gitster",
"djspiewak",
"evilsocket",
"mariotaku",
"shama",
"CamDavidsonPilon",
"dsyer",
"winterbe",
"dennybritz",
"arun-gupta",
"maryrosecook",
"killme2008",
"IanLunn",
"ruanyf",
"binux",
"nfultz",
"leah",
"suissa",
"anishathalye",
"pkrumins",
"isaacs",
"staltz",
"KittenYang",
"leebyron",
"fengmk2",
"passy",
"gorhill",
"phuslu",
"mrmrs",
"siddontang",
"daylerees",
"weavejester",
"zce",
"philsturgeon",
"oldratlee",
"josephmisiti",
"atian25",
"ebidel",
"overtrue",
"connors",
"eliben",
"Seldaek",
"joyeecheung",
"bailicangdu",
"nikic",
"codahale",
"amitshekhariitbhu",
"rakyll",
"junyanz",
"simurai",
"nicolasgramlich",
"shiffman",
"purcell",
"evanphx",
"ericelliott",
"matyhtf",
"StephenGrider",
"AdamBien",
"rtomayko",
"tomchristie",
"be5invis",
"amueller",
"dead-horse",
"remy",
"Unknwon",
"jiyinyiyong",
"Shougo",
"arunoda",
"benoitc",
"ask",
"JohnSundell",
"Raynos",
"samuelclay",
"unicodeveloper"]

for user in prepend:
    for t in range(1,3):
        string = "https://github.com/{}?page={}&tab=followers".format(user,t)
        driver.get(string)
        time.sleep(1)

        # make sure to pick the correct directory to save the files to
        # follow_button = driver.find_elements_by_xpath("//button[@type='submit']")
        follow_button = driver.find_elements_by_xpath("//input[@aria-label='Follow this person']")

        # Once page is loaded this clicks all buttons for follow
        try:
            for i in follow_button:
                i.submit()
        except:
            pass
        time.sleep(1)

driver.close()
